# Default values for tsuru-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tsuru-api:
  nameOverride: api

  service:
    type: LoadBalancer
    httpPort: 80
    httpsOnly: false
    targetHTTPPort: 8080

  indexPageTemplate: "<html><head></head><body><h1>Hello!</h1></body></html>"

  tsuruConfig:
    host: "http://tsuru-api.tsuru-system.svc.cluster.local" # requires that we always install into tsuru-system namespace
    useTLS: false

    database:
      mongodbURL: "mongodb://tsuru:tsuru@tsuru-mongodb/tsuru"

    auth:
      scheme: "native"
      native:
        tokenExpire: 2
        hashCost: 4

    queue:
      mongodbURL: "mongodb://tsuru:tsuru@tsuru-mongodb/tsuru"

    provisioner: "kubernetes"

    docker:
      registry: cr-hn-1.bizflycloud.vn
      resolve-registry-name: false
      registry-auth:
        username: APPCRED_<your_key>
        password: <your_secret_key>
      repository-namespace: <your_name_space>
      gc:
        dry-run: false
      router: ingress-router
      cluster:
        storage: mongodb
        mongo-url: "mongodb://tsuru:tsuru@tsuru-mongodb/tsuru"
        mongo-database: tsuru

    routers:
      ingress-router:
        type: api
        api-url: http://tsuru-kubernetes-router/api/ingress-nginx
        headers:
          Authorization: "Basic YWRtaW46bXlwYXNzd29yZA=="

    log:
      disableSyslog: true

    debug: true

kubernetes-router:
  service:
    type: ClusterIP
  controllerModes:
  - ingress-nginx
  ingressExpose:
    domain: cloud.127.0.0.1.nip.io
    port: 8890

  api:
    username: "admin"
    password: "mypassword"

mongodb:
  enabled: true
  image:
    tag: 4.2.21-debian-10-r8 # tsuru does not support mongo 5 yet
  auth:
    rootPassword: tsuru
    rootUser: root
    usernames:
    - tsuru
    passwords:
    - tsuru
    databases:
    - tsuru
  persistence:
    storageClass: premium-hdd1
    size: 20Gi

monitoring:
  enabled: false

ingress-nginx:
  enabled: true
  ingressClass: tsuru-nginx

certManager:
  enabled: true

registry:
  enabled: false

  # set the type of filesystem to use: filesystem, s3
  storage: filesystem

  service:
    port: 80

  configData:
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
