{{- if .Values.rpaas.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ include "tsuru-monitoring.labels" . | indent 4 }}
{{- if .Values.tsuruRules.labels }}
{{ toYaml .Values.tsuruRules.labels | indent 4 }}
{{- end }}
{{- if .Values.tsuruRules.annotations }}
  annotations:
{{ toYaml .Values.tsuruRules.annotations | indent 4 }}
{{- end }}
  name: tsuru-rpaas-rule
spec:
  groups:
  - interval: 30s
    name: tsuru-rpaas.rules
    rules:
      - expr: |
          container_memory_working_set_bytes{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_memory_working_set_bytes"

      - expr: |
          container_cpu_usage_seconds_total{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_cpu_usage_seconds_total"

      - expr: |
          container_network_receive_bytes_total{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_network_receive_bytes_total"

      - expr: |
          container_network_transmit_bytes_total{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_network_transmit_bytes_total"

      - expr: |
          container_cpu_load_average_10s{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_cpu_load_average_10s"

      - expr: |
          container_spec_memory_limit_bytes{} * on(pod) group_left(label_rpaas_service, label_rpaas_instance) kube_pod_labels{label_nginx_tsuru_io_app="nginx"}
        record: "rpaas:container_spec_memory_limit_bytes"

      - expr: |
          sum by (namespace, service_instance, service, le) (increase(nginx_vts_server_request_duration_seconds_bucket[2m]))/2
        record: "rpaas:nginx_vts_server_request_duration_seconds_bucket:increase_1m"

  - interval: 2m
    name: tsuru-rpaas.long-term
    rules:
    - expr: |
        sum by (service, service_instance, code)(irate(nginx_vts_server_requests_total{host="*",code!="total",kubernetes_container_name="nginx"}[5m]))
      record: long_term:rpaas:requests_total:irate:5m
    - expr: |
        sum by (status, service, service_instance) (irate(nginx_vts_server_cache_total{host="*"}[5m]))
      record: long_term:rpaas:cache_total:irate:5m
    - expr: |
        sum by (status, service, service_instance, upstream, backend) (irate(nginx_vts_upstream_requests_total{code!="total"}[5m]))
      record: long_term:rpaas:upstream_requests_total:irate:5m

    - expr: |
        histogram_quantile(0.5, sum by (namespace, service, service_instance, le) (sum_over_time(rpaas:nginx_vts_server_request_duration_seconds_bucket:increase_1m[5m])) >= 0)
      record: long_term:rpaas:request_duration:p50:5m

    - expr: |
        histogram_quantile(0.95, sum by (namespace, service, service_instance, le) (sum_over_time(rpaas:nginx_vts_server_request_duration_seconds_bucket:increase_1m[5m])) >= 0)
      record: long_term:rpaas:request_duration:p95:5m

    - expr: |
        histogram_quantile(0.99, sum by (namespace, service, service_instance, le) (sum_over_time(rpaas:nginx_vts_server_request_duration_seconds_bucket:increase_1m[5m])) >= 0)
      record: long_term:rpaas:request_duration:p99:5m

    # cpu
    - record: long_term:rpaas:cpu_usage:max:3m
      expr: |
        max by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (rate(container_cpu_usage_seconds_total{container!="POD", container!="", pod!=""}[3m]) *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})
    - record: long_term:rpaas:cpu_usage:min:3m
      expr: |
        min by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (sum by (pod) (rate(container_cpu_usage_seconds_total{container!="POD", container!="", pod!=""}[3m])) *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})
    - record: long_term:rpaas:cpu_usage:avg:3m
      expr: |
        avg by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (sum by (pod) (rate(container_cpu_usage_seconds_total{container!="POD", container!="", pod!=""}[3m])) *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})
    - record: long_term:rpaas:cpu_usage:sum:3m
      expr: |
        sum by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (rate(container_cpu_usage_seconds_total{container!="POD", container!="", pod!=""}[3m]) *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    - record: long_term:rpaas:cpu_throttled:sum:3m
      expr: |
        sum by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) ((
          sum by (namespace, pod) (rate(container_cpu_cfs_throttled_periods_total[3m])) /
          sum by (namespace, pod) (rate(container_cpu_cfs_periods_total[3m]))
        ) * on (namespace, pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    # memory
    - record: long_term:rpaas:memory_usage:max
      expr: |
        max by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (container_memory_working_set_bytes{container!="POD", container!="", pod!=""} *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    - record: long_term:rpaas:memory_usage:min
      expr: |
        min by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (container_memory_working_set_bytes{container!="POD", container!="", pod!=""} *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    - record: long_term:rpaas:memory_usage:avg
      expr: |
        avg by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (container_memory_working_set_bytes{container!="POD", container!="", pod!=""} *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    - record: long_term:rpaas:memory_usage:sum
      expr: |
        sum by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (container_memory_working_set_bytes{container!="POD", container!="", pod!=""} *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    ## network
    - record: long_term:rpaas:network_transmit_bytes:sum:3m
      expr: |
        sum by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (rate(container_network_transmit_bytes_total{pod!=""}[3m]) *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    - record: long_term:rpaas:network_receive_bytes:sum:3m
      expr: |
        sum by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (rate(container_network_receive_bytes_total{pod!=""}[3m]) *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})

    ## units ready
    - record: long_term:rpaas:replicas:sum
      expr: |
        sum by (label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) (kube_pod_status_ready *
        on (pod) group_left(label_rpaas_extensions_tsuru_io_service_name, label_rpaas_extensions_tsuru_io_instance_name) kube_pod_labels{label_nginx_tsuru_io_app="nginx"})
{{- end }}
